<?php

/**
 * $shimansky.biz
 *
 * Static web site core scripts
 * @package shimansky.biz
 * @author Serguei Shimansky <serguei@shimansky.biz>
 * @copyright Serguei Shimansky 10:07 24.06.2012
 * @access public
 * @version 0.2
 * @link https://bitbucket.org/englishextra/shimansky.biz
 * @link https://github.com/englishextra/shimansky.biz.git
 * @link https://gist.github.com/2981888
 * @link http://pastebin.com/y2Gs4bzE
 */
$dir = null;

$dir[] = array('/');
$dir[] = array('pages/');
$dir[] = array('pages/aids/');
$dir[] = array('pages/articles/');
$dir[] = array('pages/blog/');
$dir[] = array('pages/grammar/');
$dir[] = array('pages/more/');
$dir[] = array('pages/tests/');
$dir[] = array('m/');
$dir[] = array('m/pages/aids/');
$dir[] = array('m/pages/articles/');
$dir[] = array('m/pages/grammar/');
$dir[] = array('m/pages/tests/');
